# Generated by Django 3.0.2 on 2020-10-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='e_mail',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='details',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='e_mail',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
